# Generated by Django 4.2.4 on 2023-08-24 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_mark', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('instruction', models.TextField(null=True)),
                ('duration', models.DurationField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('no_of_questions', models.IntegerField()),
                ('exam_code', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.BooleanField(default=False)),
                ('submitted', models.BooleanField(default=False)),
                ('date_started', models.DateTimeField(default=None, null=True)),
                ('date_submitted', models.DateTimeField(default=None, null=True)),
                ('score', models.IntegerField(default=0)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exam.assessment')),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('assessment', 'candidate')},
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='candidates',
            field=models.ManyToManyField(related_name='tests', through='exam.AssessmentResult', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessment',
            name='examiner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL),
        ),
    ]
