# Generated by Django 4.2.4 on 2023-08-26 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='cardinality',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questiongrade',
            name='question',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='question.question'),
        ),
    ]
